version: 0.2
phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - public/**/*
    - src/**/*
    - package.json
    - yarn.lock
    - appspec.yml
    - scripts/**/*
